#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=ynhtest

# Retrieve arguments
domain=$1
path=$2
testbool=$3

# Save app settings
sudo yunohost app setting $app testbool -v "$testbool"

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app \
	|| (echo "Path not available: $domain$path" && exit 1)

# Copy source files
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/. $final_path

# Set permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R root:root $final_path

# If your app use a MySQL database you can use these lines to bootstrap
# a database, an associated user and save the password in app settings
# db_pwd=$(openssl rand -hex 15)
# sudo yunohost app initdb $app -p $db_pwd
# sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
# If a dedicated php-fpm process is used:
# Don't forget to modify ../conf/nginx.conf accordingly or your app will not work!
#
#sudo sed -i "s@YNH_WWW_APP@$app@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If a dedicated php-fpm process is used:
# Adjustment and copy dedicated php-fpm conf file
# Don't forget to modify ../conf/php-fpm.conf accordingly or your app will not work!
#
#sed -i "s@YNH_WWW_APP@$app@g" ../conf/php-fpm.conf
#sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/php-fpm.conf
#finalphpconf=/etc/php5/fpm/pool.d/$app.conf
#sudo cp ../conf/php-fpm.conf $finalphpconf
#sudo chown root: $finalphpconf
#sudo chmod 644 $finalphpconf


# If dedicated php-fpm process:
#
#sudo service php5-fpm reload

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
