#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=ynhtest

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
testbool=$(sudo yunohost app setting $app testbool)

# Remove trailing "/" for next commands
path=${path%/}

# Copy source files
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/. $final_path

# Set permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R root:root $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
# If a dedicated php-fpm process is used :
#
#sudo sed -i "s@YNH_WWW_APP@$app@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If a dedicated php-fpm process is used :
# Adjustment and copy dedicated php-fpm conf file
#
#sed -i "s@YNH_WWW_APP@$app@g" ../conf/php-fpm.conf
#sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/php-fpm.conf
#finalphpconf=/etc/php5/fpm/pool.d/$app.conf
#sudo cp ../conf/php-fpm.conf $finalphpconf
#sudo chown root: $finalphpconf
#sudo chmod 644 $finalphpconf

# If a dedicated php-fpm process is used :
#
#sudo service php5-fpm restart

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf

